name = "Vibe Aurora"
entry = "image"
surface_alpha = "opaque"
description = "Soft teal aurora bands with luminous mint highlights"
tags = [
    "glsl",
    "vibe"
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
