version = 1
workspace_switch_crossfade = "1500ms"

[defaults]
playlist = "vibes"
fps = 0
antialias = "auto"

[playlists.vibes]
mode = "continuous"
item_duration = "7s"
crossfade = "4s"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-grayday"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-aurora"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-neonrise"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-coralbloom"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-lilacglow"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-midnightjazz"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-solarflare"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-deepcurrent"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-sakurastream"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-mojitomist"

[[playlists.vibes.items]]
handle = "local-shaders/vibe-emberdream"

[playlists.grayday]
mode = "continuous"
item_duration = "10m"

[[playlists.grayday.items]]
handle = "local-shaders/vibe-grayday"

[playlists.simplex]
mode = "continuous"
item_duration = "10m"

[[playlists.simplex.items]]
handle = "local-shaders/simplex"

[playlists.kaleidoscope]
mode = "continuous"
item_duration = "30s"
crossfade = "3s"

[[playlists.kaleidoscope.items]]
handle = "local-shaders/kal-prismflux"

[[playlists.kaleidoscope.items]]
handle = "local-shaders/kal-petalspire"

[[playlists.kaleidoscope.items]]
handle = "local-shaders/kal-starweave"

[targets]
"workspace:1" = "grayday"
"workspace:2" = "simplex"
"workspace:3" = "kaleidoscope"
"_default" = "vibes"
