version = 1
workspace_switch_crossfade = "1500ms"

[defaults]
playlist = "vibes"
fps = 0
antialias = "auto"

[playlists.vibes]
mode = "continuous"
item_duration = "7s"
crossfade = "4s"

# Vibes
#
[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-grayday"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-aurora"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-neonrise"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-coralbloom"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-lilacglow"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-midnightjazz"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-solarflare"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-deepcurrent"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-sakurastream"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-mojitomist"

[[playlists.vibes.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-emberdream"

# Grayday
#
[playlists.grayday]
mode = "continuous"
item_duration = "10m"

[[playlists.grayday.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/vibe-grayday"

# Simplex
#
[playlists.simplex]
mode = "continuous"
item_duration = "10m"

[[playlists.simplex.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/simplex"

# Fungal Apocalypse
#
[playlists.fungal]
mode = "continuous"
item_duration = "10m"

[[playlists.fungal.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/fungal-apocalypse"

# Kaleidoscope
#
[playlists.kaleidoscope]
mode = "continuous"
item_duration = "15s"
crossfade = "1s"

[[playlists.kaleidoscope.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/kal-honeycomb2"

[[playlists.kaleidoscope.items]]
handle = "/home/nic/repos/HyprlandShaderWallpaper/local-shaders/kal-petalspire"

[targets]
"1" = "simplex"
"2" = "grayday"
"3" = "kaleidoscope"
"_default" = "fungal"
