version = 1

[defaults]
playlist = "vibes"
fps = 0
antialias = "auto"

[playlists.vibes]
mode = "continuous"
item_duration = "7s"
crossfade = "4s"

[[playlists.vibes.items]]
handle = "vibe-grayday"

[[playlists.vibes.items]]
handle = "vibe-aurora"

[[playlists.vibes.items]]
handle = "vibe-neonrise"

[[playlists.vibes.items]]
handle = "vibe-coralbloom"

[[playlists.vibes.items]]
handle = "vibe-lilacglow"

[[playlists.vibes.items]]
handle = "vibe-midnightjazz"

[[playlists.vibes.items]]
handle = "vibe-solarflare"

[[playlists.vibes.items]]
handle = "vibe-deepcurrent"

[[playlists.vibes.items]]
handle = "vibe-sakurastream"

[[playlists.vibes.items]]
handle = "vibe-mojitomist"

[[playlists.vibes.items]]
handle = "vibe-emberdream"
