version = 1
workspace_switch_crossfade = "1500ms"

[defaults]
playlist = "simplex"
fps = 0
antialias = "auto"

# Template
#
[playlists.template]
mode = "continuous"

[[playlists.template.items]]
handle = "local-shaders/template"

# Clouds
#
[playlists.clouds]
mode = "continuous"

[[playlists.clouds.items]]
handle = "shadertoy://WXXcRn"
fps = 20

# Simplex
#
[playlists.simplex]
mode = "continuous"

[[playlists.simplex.items]]
handle = "local-shaders/simplex"

[playlists.simplex-color]
mode = "continuous"

[[playlists.simplex-color.items]]
handle = "local-shaders/simplex-color"

[targets]
"_default" = "clouds"
"1" = "simplex"
