name = "Debug Black"
entry = "image"
surface_alpha = "opaque"
description = "Solid black fragment shader for crossfade debugging"
tags = ["debug", "solid-color"]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
