name = "Gray Day"
entry = "image"
surface_alpha = "opaque"
description = "Moody grayscale background"
tags = [
    "glsl"
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
