name = "Kal Petalspire"
entry = "image"
surface_alpha = "opaque"
description = "Equilateral three-mirror kaleidoscope producing a hexagonal petal mosaic"
tags = [
    "glsl",
    "kaleidoscope"
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
