name = "Kal Starweave"
entry = "image"
surface_alpha = "opaque"
description = "45-45-90 three-mirror kaleidoscope tessellating squares and rhombi with rainbow spokes"
tags = [
    "glsl",
    "kaleidoscope"
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
