name = "Simplex Noise Rotation"
entry = "image"
surface_alpha = "opaque"
description = "Simplex noise applied to two rotating layers"
tags = [
    "glsl",
    "simplexnoise",
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
