name = "Raymarching - Primitives"
entry = "image"
description = "A set of raw primitives. All except the ellipsoid are exact euclidean distances. More info here: [url=https://iquilezles.org/articles/distfunctions]https://iquilezles.org/articles/distfunctions[/url]"
tags = [
    "procedural",
    "3d",
    "raymarching",
    "distancefields",
    "primitives",
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
