version = 1
workspace_switch_crossfade = "1500ms"

[defaults]
playlist = "simplex"
fps = 0
antialias = "auto"
crossfade = "1s"

# Template
#
[playlists.simplex]
mode = "continuous"
item_duration = "5s"

[[playlists.simplex.items]]
handle = "template"

[[playlists.simplex.items]]
handle = "shadertoy://WXXcRn"
fps = 20

[[playlists.simplex.items]]
handle = "simplex"

[[playlists.simplex.items]]
handle = "simplex-color"

[targets]
"_default" = "simplex"
