version = 1

[defaults]
playlist = "debug"
fps = 10
antialias = "auto"

[playlists.debug]
mode = "continuous"
item_duration = "5s"
crossfade = "3s"

[[playlists.debug.items]]
handle = "black"

[[playlists.debug.items]]
handle = "white"

[targets]
"_default" = "debug"
