version = 1
workspace_switch_crossfade = "1500ms"

[defaults]
playlist = "vibes"
fps = 0
antialias = "auto"

[playlists.vibes]
mode = "continuous"
item_duration = "7s"
crossfade = "4s"

# Vibes
#
[[playlists.vibes.items]]
handle = "vibe-grayday"

[[playlists.vibes.items]]
handle = "vibe-aurora"

[[playlists.vibes.items]]
handle = "vibe-neonrise"

[[playlists.vibes.items]]
handle = "vibe-coralbloom"

[[playlists.vibes.items]]
handle = "vibe-lilacglow"

[[playlists.vibes.items]]
handle = "vibe-midnightjazz"

[[playlists.vibes.items]]
handle = "vibe-solarflare"

[[playlists.vibes.items]]
handle = "vibe-deepcurrent"

[[playlists.vibes.items]]
handle = "vibe-sakurastream"

[[playlists.vibes.items]]
handle = "vibe-mojitomist"

[[playlists.vibes.items]]
handle = "vibe-emberdream"

# Grayday
#
[playlists.grayday]
mode = "continuous"
item_duration = "10m"

[[playlists.grayday.items]]
handle = "vibe-grayday"

# Simplex
#
[playlists.simplex]
mode = "continuous"
item_duration = "10m"

[[playlists.simplex.items]]
handle = "simplex-color"

# Fungal Apocalypse
#
[playlists.fungal]
mode = "continuous"
item_duration = "10m"

[[playlists.fungal.items]]
handle = "fungal-apocalypse"

# Kaleidoscope
#
[playlists.kaleidoscope]
mode = "continuous"
item_duration = "15s"
crossfade = "1s"

[[playlists.kaleidoscope.items]]
handle = "kal-honeycomb2"

[[playlists.kaleidoscope.items]]
handle = "kal-petalspire"

[targets]
"1" = "simplex"
"2" = "grayday"
"3" = "kaleidoscope"
"_default" = "fungal"
