name = "Template Project"
entry = "image"
surface_alpha = "opaque"
color_space = "auto"
description = "Clone this project"
tags = [
    "glsl"
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
