version = 1

[defaults]
playlist = "shadertoy"
fps = 0
antialias = "off"

[playlists.shadertoy]
mode = "continuous"
item_duration = "60s"
crossfade = "3s"

[[playlists.shadertoy.items]]
handle = "shader://simplex-color"

[[playlists.shadertoy.items]]
handle = "shader://template"

