version = 1

[defaults]
playlist = "shadertoy"
fps = 0
antialias = "auto"

[playlists.shadertoy]
mode = "continuous"
item_duration = "300s"
crossfade = "1s"

[[playlists.shadertoy.items]]
handle = "shader://simplex-color"

[[playlists.shadertoy.items]]
handle = "shader://template"

[[playlists.shadertoy.items]]
handle = "shadertoy://XsX3zl"

[[playlists.shadertoy.items]]
handle = "shadertoy://dtfXDM"

[[playlists.shadertoy.items]]
handle = "shadertoy://3XdXRr"

