
name = "Kal Honeycomb2"
entry = "image"
surface_alpha = "opaque"
description = "three-mirror (60-60-60) kaleidoscope with honeycomb tessellation"
tags = [
    "glsl",
    "kaleidoscope"
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
