name = "Vibe Ember Dream"
entry = "image"
surface_alpha = "opaque"
description = "Ember-toned waves with smoldering glow pulses"
tags = [
    "glsl",
    "vibe"
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
