name = "Kal Prismflux"
entry = "image"
surface_alpha = "opaque"
description = "Two-mirror dihedral kaleidoscope with configurable wedge count, star facets, and rotational speed"
tags = [
    "glsl",
    "kaleidoscope"
]

[[passes]]
name = "image"
kind = "image"
source = "image.glsl"
inputs = []
