name: Cache Cleanup

on:
  # Run cache cleanup weekly to prevent unlimited growth
  schedule:
    - cron: '0 2 * * 0'  # Sunday at 2 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  cleanup-caches:
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup old caches
      uses: actions/github-script@v7
      with:
        script: |
          // Clean up caches older than 7 days
          const caches = await github.rest.actions.getActionsCacheList({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          
          const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
          
          for (const cache of caches.data.actions_caches) {
            const cacheDate = new Date(cache.created_at);
            if (cacheDate < oneWeekAgo) {
              console.log(`Deleting cache: ${cache.key} (created: ${cache.created_at})`);
              try {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });
              } catch (error) {
                console.log(`Failed to delete cache ${cache.key}: ${error.message}`);
              }
            }
          }